"use client";
import { useEffect,useState } from "react";
type Settings={minProfitBps:number;maxSlippageBps:number;maxTradeUsd:number;maxDailyLossUsd:number;minLiquidityUsd:number;opportunityTtlMs:number};
type Opportunity={id:string;input_token:string;buy_venue:string;sell_venue:string;profit_bps:number;expected_net_profit:string;status:string;detected_at:string;expires_at:string};
type Dashboard={state:{status:string;mode:string};opportunities:{count:number;active:number};trades:{count:number;successful:number};pnl:{realized:string;expected:string;trades:number;wins:number;losses:number;winRate:number;avgProfit:string};latency:{detectionToDecisionMs:number|null;decisionToSimulationMs:number|null;totalMs:number|null};events:Array<{id:number;level:string;event_type:string;payload:Record<string,unknown>;created_at:string}>;latestOpportunities:Opportunity[];settings?:Partial<Settings>};
type Solana={cluster:string;slot:string;blockHeight?:string;walletAddress?:string|null;balanceLamports?:string|null;liveTradingEnabled:boolean};
const money=(v:string|number)=>`$${Number(v||0).toFixed(4)}`;
const DEFAULT_SETTINGS:Settings={minProfitBps:30,maxSlippageBps:20,maxTradeUsd:100,maxDailyLossUsd:25,minLiquidityUsd:10000,opportunityTtlMs:1000};
export default function Home(){
 const [data,setData]=useState<Dashboard|null>(null),[solana,setSolana]=useState<Solana|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function load(){try{const [r,s]=await Promise.all([fetch("http://127.0.0.1:8787/api/dashboard",{cache:"no-store"}),fetch("http://127.0.0.1:8787/api/solana",{cache:"no-store"})]);if(!r.ok)throw new Error("Trader API unavailable");const next=await r.json() as Dashboard;setData({...next,settings:{...DEFAULT_SETTINGS,...(next.settings??{})}});if(s.ok)setSolana(await s.json());setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard")}}
 async function control(status:string){await fetch("http://127.0.0.1:8787/api/bot/control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status})});load()}
 async function saveSettings(){if(!data)return;setSaving(true);try{await fetch("http://127.0.0.1:8787/api/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...DEFAULT_SETTINGS,...(data.settings??{})})});await load()}finally{setSaving(false)}}
 const patch=(p:Partial<Settings>)=>setData(prev=>prev?{...prev,settings:{...DEFAULT_SETTINGS,...(prev.settings??{}),...p}}:prev);
 useEffect(()=>{load();const t=setInterval(load,2000);return()=>clearInterval(t)},[]);const d=data;const settings={...DEFAULT_SETTINGS,...(d?.settings??{})};
 return <div className="shell"><aside className="sidebar"><div className="brand">SOL<span>TRADER</span></div><nav className="nav"><a className="active" href="#dashboard">Dashboard</a><a href="#opportunities">Opportunities</a><a href="#performance">Performance</a><a href="#settings">Strategy</a><a href="#events">Events</a></nav></aside><main className="main">
 <header className="top"><div><div className="eyebrow">Arbitrage control center</div><div className="title">SolTrader <span className="muted">/ {d?.state.mode??"PAPER"}</span></div></div><div className="controls"><div className="status"><span className="dot"/> {d?.state.status?.toUpperCase()??"CONNECTING"}</div><button className="btn" onClick={()=>control(d?.state.status==="running"?"paused":"running")}>{d?.state.status==="running"?"Pause":"Start"}</button><button className="btn danger" onClick={()=>control("stopped")}>Emergency Stop</button></div></header>
 {error&&<div className="card error">{error}. Make sure PostgreSQL, Redis and the trader API are running.</div>}
 <section id="dashboard" className="grid"><Metric label="24h realized P&L" value={money(d?.pnl.realized??"0")} positive={Number(d?.pnl.realized??0)>=0}/><Metric label="Expected P&L" value={money(d?.pnl.expected??"0")}/><Metric label="Opportunities" value={String(d?.opportunities.count??0)} sub={`${d?.opportunities.active??0} active`}/><Metric label="Paper trades" value={String(d?.trades.count??0)} sub={`${d?.trades.successful??0} completed`}/></section>
 <section className="section"><div className="section-head"><h2>Network & risk</h2><span className="pill green">{solana?.cluster??"—"}</span></div><div className="panel-grid"><div className="card"><Setting label="Current slot" value={solana?.slot??"—"} readOnly/><Setting label="Block height" value={solana?.blockHeight??"—"} readOnly/><Setting label="Wallet" value={solana?.walletAddress??"not configured"} readOnly/></div><div className="card"><div className="label">RISK / EXECUTION</div><div className="metric">{d?.pnl.winRate?`${(d.pnl.winRate*100).toFixed(1)}%`:"0.0%"}</div><div className="sub">win rate · {d?.pnl.wins??0} wins / {d?.pnl.losses??0} losses</div><div className="sub">daily loss limit: ${settings.maxDailyLossUsd}</div><div className="sub">live execution: {solana?.liveTradingEnabled?"enabled":"disabled"}</div></div></div></section>
 <section id="opportunities" className="section"><div className="section-head"><h2>Live opportunity feed</h2><span className="muted">2s refresh</span></div><div className="card"><table className="table"><thead><tr><th>Pair</th><th>Buy</th><th>Sell</th><th>Edge</th><th>Expected net</th><th>Status</th></tr></thead><tbody>{(d?.latestOpportunities??[]).map(o=><tr key={o.id}><td>SOL / USDC</td><td>{o.buy_venue}</td><td>{o.sell_venue}</td><td className="positive">{Number(o.profit_bps).toFixed(1)} bps</td><td>{money(o.expected_net_profit)}</td><td><span className="pill green">{o.status}</span></td></tr>)}{!d?.latestOpportunities?.length&&<tr><td colSpan={6} className="muted">Waiting for the scanner to produce opportunities…</td></tr>}</tbody></table></div></section>
 <section id="performance" className="section"><div className="section-head"><h2>Performance & execution health</h2></div><div className="panel-grid"><div className="card"><div className="label">REALIZED P&L</div><div className={`metric ${Number(d?.pnl.realized??0)>=0?"positive":"negative"}`}>{money(d?.pnl.realized??"0")}</div><div className="sub">Average trade: {money(d?.pnl.avgProfit??"0")}</div><div className="chart">Historical P&L is available from <code>/api/analytics/pnl</code>.</div></div><div className="card"><div className="label">ENGINE LATENCY</div><Setting label="Detection → decision" value={`${d?.latency.detectionToDecisionMs?.toFixed(1)??"—"} ms`} readOnly/><Setting label="Decision → simulation" value={`${d?.latency.decisionToSimulationMs?.toFixed(1)??"—"} ms`} readOnly/><Setting label="Total" value={`${d?.latency.totalMs?.toFixed(1)??"—"} ms`} readOnly/></div></div></section>
 <section id="settings" className="section"><div className="section-head"><h2>Live strategy controls</h2><button className="btn" disabled={saving} onClick={saveSettings}>{saving?"Saving…":"Apply settings"}</button></div><div className="card"><Setting label="Minimum profit (bps)" value={String(settings.minProfitBps)} onChange={v=>patch({minProfitBps:Number(v)})}/><Setting label="Maximum slippage (bps)" value={String(settings.maxSlippageBps)} onChange={v=>patch({maxSlippageBps:Number(v)})}/><Setting label="Maximum trade (USD)" value={String(settings.maxTradeUsd)} onChange={v=>patch({maxTradeUsd:Number(v)})}/><Setting label="Maximum daily loss (USD)" value={String(settings.maxDailyLossUsd)} onChange={v=>patch({maxDailyLossUsd:Number(v)})}/><Setting label="Minimum liquidity (USD)" value={String(settings.minLiquidityUsd)} onChange={v=>patch({minLiquidityUsd:Number(v)})}/><Setting label="Opportunity TTL (ms)" value={String(settings.opportunityTtlMs)} onChange={v=>patch({opportunityTtlMs:Number(v)})}/></div></section>
 <section id="events" className="section"><div className="section-head"><h2>Engine events</h2></div><div className="events">{(d?.events??[]).map(e=><div className="event" key={e.id}><time>{new Date(e.created_at).toLocaleTimeString()}</time><strong>{e.level.toUpperCase()}</strong><span>{e.event_type}</span><span className="muted">{JSON.stringify(e.payload)}</span></div>)}</div></section>
 </main></div>}
function Metric({label,value,sub,positive}:{label:string;value:string;sub?:string;positive?:boolean}){return <div className="card"><div className="label">{label}</div><div className={`metric ${positive?"positive":""}`}>{value}</div>{sub&&<div className="sub">{sub}</div>}</div>}
function Setting({label,value,onChange,readOnly=false}:{label:string;value:string;onChange?:(v:string)=>void;readOnly?:boolean}){return <div className="setting"><span>{label}</span><input value={value} readOnly={readOnly||!onChange} onChange={e=>onChange?.(e.target.value)}/></div>}
