import type { Config } from "../config/env.js";
import { getRuntimeSettings } from "../config/runtime-settings.js";
import { SimulatedQuoteProvider } from "../market/simulator.js";
import { JupiterQuoteProvider } from "../market/jupiter.js";
import { OpportunityScanner } from "../strategy/scanner.js";
import { PaperExecutionEngine } from "./paper-engine.js";
import { RiskEngine } from "./risk-engine.js";
import { getPostgresPool } from "../storage/postgres.js";
import { recordExecutionTelemetry,recordMarketSnapshot } from "./telemetry.js";
const SOL_MINT="So11111111111111111111111111111111111111112",USDC_MINT="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
export class TraderLoop{private timer:NodeJS.Timeout|undefined;private running=false;constructor(private readonly config:Config){}start(){if(this.timer)return;this.running=true;void this.tick();this.timer=setInterval(()=>void this.tick(),2000)}pause(){this.running=false}resume(){this.running=true;void this.tick()}stop(){if(this.timer)clearInterval(this.timer);this.timer=undefined;this.running=false}
 private async tick(){if(!this.running)return;try{const settings=await getRuntimeSettings(),scanConfig={...this.config,...settings},amount=BigInt(Math.max(1,Math.floor(settings.maxTradeUsd*1_000_000))),provider=this.config.quoteProvider==="jupiter"?new JupiterQuoteProvider(this.config.jupiterApiKey?{baseUrl:this.config.jupiterApiUrl,apiKey:this.config.jupiterApiKey}:{baseUrl:this.config.jupiterApiUrl}):new SimulatedQuoteProvider();const quoteStarted=Date.now(),quotes=await provider.getQuotes(SOL_MINT,USDC_MINT,amount);for(const quote of quotes)await recordMarketSnapshot(quote.slot,provider.name,quote.inputMint,quote.outputMint,quote.amountIn,quote.amountOut,Date.now()-quoteStarted);if(this.config.quoteProvider==="jupiter"){await getPostgresPool().query("INSERT INTO bot_events (level,event_type,payload) VALUES ($1,$2,$3)",["info","market_quote",JSON.stringify({provider:provider.name,quotes:quotes.length,latencyMs:Date.now()-quoteStarted})]);return}const opportunities=await new OpportunityScanner(scanConfig,provider).scan({inputMint:SOL_MINT,outputMint:USDC_MINT,amountIn:amount}),risk=new RiskEngine(scanConfig),engine=new PaperExecutionEngine();for(const opportunity of opportunities.slice(0,3)){const started=Date.now(),decision=await risk.approve(opportunity);await getPostgresPool().query("INSERT INTO risk_events (opportunity_id,decision,reason) VALUES ($1,$2,$3)",[opportunity.id,decision.approved?"approved":"rejected",decision.reason??null]);if(!decision.approved)continue;try{const decisionAt=Date.now();await engine.execute(opportunity);await recordExecutionTelemetry({opportunityId:opportunity.id,status:"paper_executed",detectionToDecisionMs:decisionAt-opportunity.detectedAt,decisionToSimulationMs:Date.now()-decisionAt,totalMs:Date.now()-started})}finally{await risk.release(decision.lockKey)}}await getPostgresPool().query("INSERT INTO bot_events (level,event_type,payload) VALUES ($1,$2,$3)",["info","scanner_tick",JSON.stringify({provider:provider.name,opportunities:opportunities.length,settings})])}catch(error){await getPostgresPool().query("INSERT INTO bot_events (level,event_type,payload) VALUES ($1,$2,$3)",["error","scanner_error",JSON.stringify({message:error instanceof Error?error.message:String(error)})])}}}
